[template]
src = "nginx.tmpl"
dest = "/etc/nginx/sites-enabled/app.conf"
owner = "nginx"
mode = "0644"
keys = [
  "/services/appname/upstream",
]
check_cmd = "/usr/sbin/nginx -t"
reload_cmd = "/usr/sbin/service nginx reload"
